packages:
  - "packages/*"
  - "examples/*"
  - "www/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.3'
  - '@turbo/darwin-arm64@2.10.3'
  - '@turbo/linux-64@2.10.3'
  - '@turbo/linux-arm64@2.10.3'
  - '@turbo/windows-64@2.10.3'
  - '@turbo/windows-arm64@2.10.3'
  - turbo@2.10.3
