// This file is generated by next-typesafe-url
// Do not edit this file directly.

// @generated
// prettier-ignore
/* eslint-disable */


declare module "@@@next-typesafe-url" {
  import type { InferRoute, StaticRoute } from "next-typesafe-url";
  
  interface DynamicRouter {
    "/foo/[id]/nest": InferRoute<import("./src/app/(test)/foo/[id]/nest/route-type").RouteType>;
    "/foo/[id]": InferRoute<import("./src/app/(test)/foo/[id]/route-type").RouteType>;
    "/client/[...client]": InferRoute<import("./src/app/client/[...client]/route-type").RouteType>;
    "/jsonRoute/[foo]": InferRoute<import("./src/app/jsonRoute/[foo]/route-type").RouteType>;
    "/transform": InferRoute<import("./src/app/transform/route-type").RouteType>;
    "/[slug]/[...foo]": InferRoute<import("./src/app/[slug]/[...foo]/route-type").RouteType>;
    "/dynamic": InferRoute<import("./src/pages/dynamic").RouteType>;
  }

  interface StaticRouter {
    "/js-static-route": StaticRoute;
    "/mdx-route": StaticRoute;
    "/": StaticRoute;
    "/static": StaticRoute;
  }
}
